SRCDIR=src
default: all

all: 
	(cd $(SRCDIR) && $(MAKE)); done

clean:
	(cd $(SRCDIR) && $(MAKE) clean); done

distclean:
	(cd $(SRCDIR) && $(MAKE) clean && $(MAKE) distclean); done


.PHONY: all clean distclean